version: "3.8"

services:
  frontend:
    container_name: videoactive_frontend_container
    build:
      context: ./videoactive-client/video-call
    image: kc012/videoactive-client:latest
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
    restart: unless-stopped

  backend:
    container_name: videoactive_backend_container
    build:
      context: ./videoactive-server/VideoActive
    image: kc012/videoactive-server:latest
    ports:
      - "5000:5000"
    restart: unless-stopped
